version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    environment:
      - ENVIRONMENT=production
      - MODEL_DIR=/app/models
      - DATA_PATH=/app/data/Mobile_Security_Dataset.csv
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  # MongoDB for storing analysis results (optional)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=securepassword

volumes:
  mongodb_data: